<?php
get_header();
get_template_part('template/index','slider');
get_template_part('template/index','services');
get_template_part('template/index','woobests');
get_template_part('template/index','offer');
get_template_part('template/index','new-products');
get_template_part('template/index','special-offers');
get_template_part('template/index','bestselling');
get_template_part('template/index','customer');
get_template_part('template/index','ads');
get_template_part('template/index','support');
get_template_part('template/index','most-viewed');
get_template_part('template/index','preorder');
get_template_part('template/index','tabslider');
get_template_part('template/index','blog');
get_footer();
?>